name: bankx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated:
  fl_chart: ^0.20.1
  page_transition: ^2.0.5
  google_maps_flutter: ^2.1.2
  local_auth: ^1.1.11
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.3
  lottie: ^1.2.2
  path: ^1.8.0
  path_provider: ^2.0.9
  syncfusion_flutter_signaturepad: ^19.4.54
  shared_preferences: ^2.0.13
  flutter_rating_bar: ^4.0.0
  http: ^0.13.4
  #aws_rekognition_api: ^0.2.0
  easy_signature_pad: ^1.0.6
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  google_sign_in: ^5.2.4
  http_parser: ^4.0.0
  plugin_platform_interface: ^2.0.0
  intl: ^0.17.0
  archive: ^3.3.0
  image: ^3.1.3
  flutter_pdfview: ^1.2.1
  mask_text_input_formatter: ^2.3.0
  email_validator: ^2.0.1
  flutter_spinkit: ^5.1.0
  select_form_field: ^2.2.0
  dropdown_button2: ^1.3.0
  cool_alert: ^1.1.0
  argon_buttons_flutter: ^1.1.0
  google_ml_kit:
  animate_do: ^2.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

module:
  androidX: true

flutter: 
  uses-material-design: true
 
  assets:
    - assets/user/
    - assets/
   
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
